export default {
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE",
    TIMEOUT: "TIMEOUT",
    REJECTED: "REJECTED",
    SHORT_CIRCUITED: "SHORT_CIRCUITED",
    FALLBACK_SUCCESS: "FALLBACK_SUCCESS",
    FALLBACK_FAILURE: "FALLBACK_FAILURE",
    FALLBACK_REJECTION: "FALLBACK_REJECTION",
    EXCEPTION_THROWN: "EXCEPTION_THROWN",
    BAD_REQUEST: "BAD_REQUEST",
    RESPONSE_FROM_CACHE: "RESPONSE_FROM_CACHE"
};
